import { ROUTES } from '@/constants/routes';
import type { PageContentEntry } from '@/types';

export const SITE_PAGES = {
  home: {
    path: ROUTES.home,
    title: 'Home',
    description: 'Placeholder route for the STAYCT home page.',
    priority: 1,
    changeFrequency: 'weekly',
    sitemap: true,
  },
  about: {
    path: ROUTES.about,
    title: 'About',
    description: 'Placeholder route for the STAYCT about page.',
    priority: 0.7,
    changeFrequency: 'monthly',
    sitemap: true,
  },
  contact: {
    path: ROUTES.contact,
    title: 'Contact',
    description: 'Placeholder route for the STAYCT contact page.',
    priority: 0.6,
    changeFrequency: 'monthly',
    sitemap: true,
  },
  pricing: {
    path: ROUTES.pricing,
    title: 'Pricing',
    description: 'Placeholder route for the STAYCT pricing page.',
    priority: 0.7,
    changeFrequency: 'monthly',
    sitemap: true,
  },
  features: {
    path: ROUTES.features,
    title: 'Features',
    description: 'Placeholder route for the STAYCT features page.',
    priority: 0.7,
    changeFrequency: 'monthly',
    sitemap: true,
  },
  resources: {
    path: ROUTES.resources,
    title: 'Resources',
    description: 'Placeholder route for the STAYCT resources page.',
    priority: 0.6,
    changeFrequency: 'monthly',
    sitemap: true,
  },
  help: {
    path: ROUTES.help,
    title: 'Help',
    description: 'Placeholder route for the STAYCT help page.',
    priority: 0.5,
    changeFrequency: 'monthly',
    sitemap: true,
  },
  cities: {
    path: ROUTES.cities,
    title: 'Cities',
    description: 'Placeholder route for the STAYCT city index.',
    priority: 0.7,
    changeFrequency: 'weekly',
    sitemap: true,
  },
  search: {
    path: ROUTES.search,
    title: 'Search',
    description: 'Placeholder route for the STAYCT search page.',
    priority: 0.3,
    changeFrequency: 'monthly',
    sitemap: false,
    noIndex: true,
  },
  operators: {
    path: ROUTES.operators,
    title: 'Operators',
    description: 'Placeholder route for the STAYCT operator hub.',
    priority: 0.6,
    changeFrequency: 'monthly',
    sitemap: true,
  },
  operatorsOwners: {
    path: ROUTES.operatorsOwners,
    title: 'Owners',
    description: 'Placeholder route for the STAYCT owner operator page.',
    priority: 0.5,
    changeFrequency: 'monthly',
    sitemap: true,
  },
  operatorsManagers: {
    path: ROUTES.operatorsManagers,
    title: 'Managers',
    description: 'Placeholder route for the STAYCT manager operator page.',
    priority: 0.5,
    changeFrequency: 'monthly',
    sitemap: true,
  },
  operatorsTenants: {
    path: ROUTES.operatorsTenants,
    title: 'Tenants',
    description: 'Placeholder route for the STAYCT tenant operator page.',
    priority: 0.5,
    changeFrequency: 'monthly',
    sitemap: true,
  },
} as const satisfies Record<string, PageContentEntry>;

export const SITE_SITEMAP_ENTRIES = Object.values(SITE_PAGES).filter((page) => page.sitemap !== false);
