import { ROUTES } from '@/constants/routes';
import type { PageContentEntry } from '@/types';

export const SITE_PAGES = {
  home: {
    path: ROUTES.home,
    title: 'Home',
    description: 'STAYCT home page for rental accommodation discovery and operator onboarding.',
    priority: 1,
    changeFrequency: 'weekly',
    sitemap: true,
  },
  about: {
    path: ROUTES.about,
    title: 'About',
    description: 'Learn what STAYCT is, who it serves, and how the platform is structured.',
    priority: 0.7,
    changeFrequency: 'monthly',
    sitemap: true,
  },
  contact: {
    path: ROUTES.contact,
    title: 'Contact',
    description: 'Contact STAYCT at support@stayct.in or +91 91363 37031 for support, business enquiries, and operator discussions.',
    priority: 0.6,
    changeFrequency: 'monthly',
    sitemap: true,
  },
  pricing: {
    path: ROUTES.pricing,
    title: 'Pricing',
    description: 'Understand the pricing direction for seekers and operators.',
    priority: 0.7,
    changeFrequency: 'monthly',
    sitemap: true,
  },
  features: {
    path: ROUTES.features,
    title: 'Features',
    description: 'See the core discovery and operator capabilities STAYCT exposes today.',
    priority: 0.7,
    changeFrequency: 'monthly',
    sitemap: true,
  },
  resources: {
    path: ROUTES.resources,
    title: 'Resources',
    description: 'Find guides, references, and supporting material for the public site.',
    priority: 0.6,
    changeFrequency: 'monthly',
    sitemap: true,
  },
  help: {
    path: ROUTES.help,
    title: 'Help',
    description: 'Get help from STAYCT with clear support actions by email or phone.',
    priority: 0.5,
    changeFrequency: 'monthly',
    sitemap: true,
  },
  cities: {
    path: ROUTES.cities,
    title: 'Cities',
    description: 'Browse city-level entry points for discovery.',
    priority: 0.7,
    changeFrequency: 'weekly',
    sitemap: true,
  },
  search: {
    path: ROUTES.search,
    title: 'Search',
    description: 'Search verified stays by category, city, and other discovery filters.',
    priority: 0.3,
    changeFrequency: 'monthly',
    sitemap: false,
    noIndex: true,
  },
  operators: {
    path: ROUTES.operators,
    title: 'Operators',
    description: 'Entry point for owners, managers, and operators who want to list a property.',
    priority: 0.6,
    changeFrequency: 'monthly',
    sitemap: true,
  },
  operatorsOwners: {
    path: ROUTES.operatorsOwners,
    title: 'Owners',
    description: 'Owner-focused entry point for listing and property discovery workflows.',
    priority: 0.5,
    changeFrequency: 'monthly',
    sitemap: true,
  },
  operatorsManagers: {
    path: ROUTES.operatorsManagers,
    title: 'Managers',
    description: 'Manager-focused entry point for day-to-day property operations.',
    priority: 0.5,
    changeFrequency: 'monthly',
    sitemap: true,
  },
  operatorsTenants: {
    path: ROUTES.operatorsTenants,
    title: 'Tenants',
    description: 'Tenant-focused entry point for communication and accommodation support.',
    priority: 0.5,
    changeFrequency: 'monthly',
    sitemap: true,
  },
  appLogin: {
    path: ROUTES.appLogin,
    title: 'App Login',
    description: 'Open the STAYCT operator app and continue into the management workspace.',
    priority: 0.4,
    changeFrequency: 'monthly',
    sitemap: false,
    noIndex: true,
  },
  privacy: {
    path: ROUTES.privacy,
    title: 'Privacy',
    description: 'Review how the public site handles data, tracking, and contact information.',
    priority: 0.3,
    changeFrequency: 'yearly',
    sitemap: true,
  },
  terms: {
    path: ROUTES.terms,
    title: 'Terms',
    description: 'Review the website terms that apply to public STAYCT usage.',
    priority: 0.3,
    changeFrequency: 'yearly',
    sitemap: true,
  },
} as const satisfies Record<string, PageContentEntry>;

export const SITE_SITEMAP_ENTRIES = Object.values(SITE_PAGES).filter((page) => page.sitemap !== false);
